import turtle as t
t.bgcolor("green")
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(200)
 t.right(90)
t.penup()
t.goto(0,0)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(30)
 t.right(90)
t.end_fill()
t.penup()
t.goto(0,-170)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(30)
 t.right(90)
t.end_fill()
t.penup()
t.goto(0,-30)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(30)
 t.right(90)
t.end_fill()
t.penup()
t.goto(0,-140)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(30)
 t.right(90)
t.end_fill()
t.penup()
t.goto(0,-60)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
for kuy in range(2):
 t.forward(300)
 t.right(90)
 t.forward(80)
 t.right(90)
t.end_fill()